### ISSUE TITLE
Logic behind TXT limits?

### ISSUE THREAD

**Issue by indolering** [tobez/validns#44]
Validns [throws an error](https://github.com/tobez/validns/blob/master/txt.c#L31) when the number of content fields for a TXT records exceeds 20, a total of 5100 bytes.  Did you find a hard limit in one of the major resolvers or did this just sound like a sane upper limit?

**Comment by tobez** [comment]
Hello,

On Wed, Oct 07, 2015 at 04:45:55PM -0700, Zach Lym wrote:
> Validns throws an error when the number of content fields for a TXT records
> exceeds 20, a total of 5100 bytes. Did you find a hard limit in one of the
> major resolvers or did this just sound like a sane upper limit?

Frankly, it was a "why would anyone want to use more than that?" limit.

I'll see about reworking the code to not employ any fixed limits there.

\Anton.
-- 
Our society can survive even a large amount of irrational regulation.
  -- John McCarthy

**Comment by indolering** [comment]
@tobez There is an overall limit of 65535 characters for the rdata value but I'm trying to figure out if there is an implicit limit.  Have you tried testing major resolvers to see when they begin to choke?
