### ISSUE TITLE
Counting of RR per type

### ISSUE THREAD

**Issue by pfedick** [tobez/validns#45]
When reading a zone file, the number of RR per type should be counted and reported at the end. The output can be used to do further validation, e.g. compare the number of records with a master database or with previous runs.

Example:

```
record count by type:
             A: 1234
            NS: 1234
           SOA: 1
            MX: 1234
          AAAA: 1234
           SRV: 1
            DS: 1234
         RRSIG: 1234
        DNSKEY: 2
         NSEC3: 1234
    NSEC3PARAM: 1
```

Regards,
Patrick

**Comment by tobez** [comment]
Implemented.  You have to specify -s at least twice to get this behavior.
