### ISSUE TITLE
Check for weak ECDSA signatures

### ISSUE THREAD

**Issue by stirnim** [tobez/validns#52]
A policy check which could recover the private key would be interesting.

See http://bitcoin.stackexchange.com/questions/35848/recovering-private-key-when-someone-uses-the-same-k-twice-in-ecdsa-signatures

**Comment by stirnim** [comment]
Probably not worth implementing this idea. OpenSSL (which most signer use) implements RFC 6979 (Deterministic Usage of the Digital Signature Algorithm (DSA) and Elliptic Curve Digital Signature Algorithm (ECDSA)). See https://github.com/openssl/openssl/blob/master/crypto/ec/ecdsa_ossl.c#L132

**Comment by tobez** [comment]
Probably not worth to implement, given there are many things of higher priority to fix/add.
